
import NextTopLoader from 'nextjs-toploader'
import './globals.css'



export const metadata = {
  title: 'Full stack news portal app.',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <NextTopLoader color="#6ED1EC" height={2} speed={200} showSpinner={false}/>
        </body>
    </html>
  )
}
